//function for handling signals
     //invalid keystrokes are ignored and keystrokes are not echoed back
     //if ctrl-c is pressed the clean up program
          //To prevent those kinds of problems, add the code necessary to handle the signal generated by Ctrl-C. Your signal handler 
	  //should use tcsetattr to reset the terminal mode to the settings that were saved when the program started (which will normally
	  //be the default of canonical mode with echo turned on). It should then display a message indicating that the terminal settings
	  //have been restored and the program is terminating. It should then terminate.
     //If the user types a 'q', then your program exits
     //If the user types a space, then your program displays the next 23 lines of the file. call printLines and pass in the amount of
     // lines needs
     //If the user presses the ENTER key, then just the next line of the file is displayed. call printLines and pass in the 1 line that
      //is needed
 

//function for handling file input
     //if no file then copy stdin to stdout (it allows for pipes and redirections)
          //print out 'Bytes' plus the number
               //You can open the terminal device using either open, which returns a file descriptor, or fopen, which returns a file
		//pointer. File descriptors are declared as integers: int fd; whereas file pointers are declared like this: FILE *fp;
	//int fd_tty;
	//FILE *fp_tty;

	//fd_tty = open("/dev/tty", O_RDONLY);

	//fp_tty = fdopen(fd_tty, "r");

     //if file then copy the contents of the named file to stdout (only one argument/file is expected)
          //two % signs to create a % sign
          //The prompt for the first screen will show the name of the file and the percentage that has been displayed:  myFile.txt 14%  
          // After the first screen the prompt should show only the percentage that has been displayed.  28%  

//function for printing lines(takes int that is the amount of lines)
     //track the line position
     //print amount of lines requested
          //check for number of lines left and 
          //if the line size is the same or less then what is left then print normally 
          //else if the line size is more then what is left then just print the rest out.
     
 

//main function
     //program should use tcgetattrs to save the terminal attributes when it first starts. Before terminating it should use tcsetattrs to restore the original terminal             attributes.



//Notes
	//To erase a character from the screen, display a backspace character (\b), a blank, and another backspace character.
	//To display a percent (%) sign using printf, use two % symbols in a row.
	//For reverse video, print \033[7m to start reverse video, and then \033[m to end reverse video. See the code on page 22 of the 
	// Molay book for an example.
	//You can use the reset command to restore your terminal settings if your program doesn't.
